### ISSUE TITLE
Python triple quoted comments not recognized

### ISSUE THREAD

**Issue by FrancescoGd** [tokyo-night/tokyo-night-vscode-theme#89]
Hi, first of all let me tell that i **really love** this beautiful theme, so thank you!
Sadly I had to switch back to using Dracula though because it mismatches Python's multiline comments inside triple quotes for strings (see attached images) and it's a bit confusing.
Any hints?
VSCode version: 1.89.1
Theme version: 1.0.6

![python comment with Tokyo Night](https://github.com/enkia/tokyo-night-vscode-theme/assets/32357315/700b69ee-6ae6-4e0b-b7e2-349bad8fc4c2)

![python comment with Dracula](https://github.com/enkia/tokyo-night-vscode-theme/assets/32357315/a10b7f89-59a8-4576-9762-00cfadf9fde7)

**Comment by FrancescoGd** [comment]
Replying to myself, I see that other themes have these lines, don't know if it's relevant:

```
- name: Docstrings
  scope:
  - string.quoted.docstring.multi
  - string.quoted.docstring.multi.python punctuation.definition.string.begin
  - string.quoted.docstring.multi.python punctuation.definition.string.end
  - string.quoted.docstring.multi.python constant.character.escape
  settings:
    foreground: *COMMENT
```
